config/routes.rb
Rails.application.routes.draw do
  root 'movies#index'
  resources :locations

  resources :movies do
    resources :reviews
  end

end

app/models/location.rb
class Location < ActiveRecord::Base
end

app/models/movie.rb
class Movie < ActiveRecord::Base
	has_many :reviews, dependent: :destroy

	validates :title, :variety, :rating, :total_gross, presence: true
	validates :image_file_name, allow_blank: true,
	        format: {
	        	with:  /\w+\.(gif|jpg|png)\z/i,
	        	message:"must reference a GIF, JPG, or PNG image"
	        }

	def self.upcoming
		where('released_on >= ?', Time.now).order(:released_on)
    end
    def free?
    price.blank? || price.zero?
    end
end  
  

app/models/movie_spec.rb
it "has many reviews" do
  movie = Movie.new(movie_attributes)

  review1 = movie.reviews.new(review_attributes)
  review2 = movie.reviews.new(review_attributes)

  expect(movie.reviews).to include(review1)
  expect(movie.reviews).to include(review2)
end

it "deletes associated reviews" do
  movie = Movie.create(movie_attributes)

  movie.reviews.create(review_attributes)

  expect { 
    movie.destroy
  }.to change(Review, :count).by(-1)
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :movie

  validates :name, presence: true
  validates :comment, length: { minimum: 4 }
  STARS = [1, 2, 3, 4, 5]

validates :stars, inclusion: { 
  in: STARS,
  message: "must be between 1 and 5"
}
end

app/models/review_spec.rb
require 'spec_helper'

describe "A review" do

  it "belongs to a movie" do
    movie = Movie.create(movie_attributes)

    review = movie.reviews.new(review_attributes)

    expect(review.movie).to eq(movie)
  end

  it "with example attributes is valid" do
    review = Review.new(review_attributes)

    expect(review.valid?).to eq(true)
  end

  it "requires a name" do
    review = Review.new(name: "")

    review.valid? # populates errors

    expect(review.errors[:name].any?).to eq(true)
  end

  it "requires a comment" do
    review = Review.new(comment: "")

    review.valid?
    
    expect(review.errors[:comment].any?).to eq(true)
  end

  it "requires a comment over 3 characters" do
    review = Review.new(comment: "X" * 3)

    review.valid?

    expect(review.errors[:comment].any?).to eq(true)
  end

  it "accepts star values of 1 through 5" do
    stars = [1, 2, 3, 4, 5]
    stars.each do |star|
      review = Review.new(stars: star)

      review.valid?

      expect(review.errors[:stars].any?).to eq(false)
    end
  end

  it "rejects invalid star values" do
    stars = [-1, 0, 6]
    stars.each do |star|
      review = Review.new(stars: star)

      review.valid?

      expect(review.errors[:stars].any?).to eq(true)
      expect(review.errors[:stars].first).to eq("must be between 1 and 5")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:address, :latitude, :longitude)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    # this array is being replaced with 
    # @movies = ['The Equalizer', 'The Judge', 'The Book Of Life', 'John Wick', 'Gone Girl', 'Dracula Untold', 'Fury', 'Annabelle']
    # which is beign call my the model
    @movies = Movie.all
  end

  def new
    @movie = Movie.new
    @response = HTTParty.get('http://api.rottentomatoes.com/api/public/v1.0/lists/movies/box_office.json?limit=16&country=us&apikey=echs8gdkqgzwsksygfbc6vz9')

  end

  def show
    @movie = Movie.find(params[:id])
  end

  def create
    movie_params = params.require(:movie).
                    permit(:variety, :title, :rating, :total_gross, :released_on, :image_file_name)
    @movie = Movie.new(movie_params)
    if @movie.save
       redirect_to @movie
     else
      render :new
    end
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    movie_params = params.require(:movie).
                    permit(:variety, :title, :rating, :total_gross, :released_on, :image_file_name)
    @movie.update(movie_params)
    redirect_to @movie
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to @movie
end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def index
      @movie = Movie.find(params[:movie_id])
      @reviews = @movie.reviews
  end

  def new
  	@movie = Movie.find(params[:movie_id])
  	@review = @movie.reviews.new
  end

  def create
  	@movie = Movie.find(params[:movie_id])
  	@review = @movie.reviews.new(review_params)
  	if @review.save
  		redirect_to movie_reviews_path(@movie)
  		         
  	else
  		render :new
  	end
  end

private
   def review_params
   	params.require(:review).permit(:name, :stars, :comment)
   end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
	def format_total_gross(movie)
  end
  def image_for(movie)
  	if movie.image_file_name.blank?
  		image_tag 'placeholder.png'
  	else
  	   image_tag movie.image_file_name
  	end
  		
  	end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>



<header id="page-header">
	<h1>The Movie Tracker</h1>

</header>
   <aside id="sidebar">
	<nav>
		<ul>
			<li><%= link_to "All Movies", movies_path %></li>
			<li><%= link_to "Add New Movie", new_movie_path %></li>
		</ul>
	</nav>
</aside>	

<%= yield %>

<footer id="page-footer">
	<p>
		Copyright &copy; 2014 The Ultimate Design
	</p>
</footer>

</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<h1>Listing locations</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.address %></td>
        <td><%= location.latitude %></td>
        <td><%= location.longitude %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @location.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @location.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @location.longitude %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/movies/_form.html.erb
<p> @response </p>
<%= form_for(@movie) do |f| %>
 <%= @movie.errors.full_messages.to_sentence %>
<p>
	<%= f. label :title %><br>
	<%= f. text_field :title, autofocus: true %>
</p>
<p>
	<%= f.label :variety %><br>
	<%= f.text_field :variety %>
</p>
<p>
	<%= f.label :rating %><br>
	<%= f.text_field :rating %>
</p>
<p>
	<%= f.label :total_gross %><br>
	<%= f.number_field :total_gross %>
</p>
<p>
	<%= f.label :released_on %><br>
	<%= f.datetime_select :released_on %>
</p>
    <%= f.label :image_file_name %><br/>
    <%= f.text_field :image_file_name, size: 30,
         placeholder: "GIF, JPG, or PNG file name" %>
<p>
<p>
	<%= f.label :capacity %><br/>
	<%= f.number_field :capacity %>
</p>
	<%= f.submit %>
	<%= link_to "Cancel", movies_path %>
</p>
<% end -%>

app/views/movies/create.html.erb
<h1>Movies#create</h1>
<p>Find me in app/views/movies/create.html.erb</p>

app/views/movies/destroy.html.erb
<h1>Movies#destroy</h1>
<!-- <p>Find me in app/views/movies/destroy.html.erb</p> -->

app/views/movies/edit.html.erb
<h1>Editing <%= @movie.title %></h1>
<!-- The below was commented out and a Partials under views
/movies _form.html.erb -->
<%= render 'form' %>

<!-- <%= form_for(@movie) do |f| %>
<p>
	<%= f. label :title %><br>
	<%= f. text_field :title, autofocus: true %>
</p>
<p>
	<%= f.label :variety %><br>
	<%= f.text_field :variety %>
</p>
<p>
	<%= f.label :rating %><br>
	<%= f.text_field :rating %>
</p>
<p>
	<%= f.label :total_gross %><br>
	<%= f.number_field :total_gross %>
</p>
<p>
	<%= f.label :released_on %><br>
	<%= f.datetime_select :released_on %>
</p>
<p>
	<%= f.submit %>
	<%= link_to "Cancel", movies_path %>
</p>
<% end -%> -->

app/views/movies/index.html.erb
<body>
<div class="large-4 columns">.</div>
<div class="large-4 columns">

<h1><%= pluralize(@movies.size, 'Movie') %> Top in the Area!</h1>
<!-- The below link was move to the application.html.erb page -->
<!-- <%= link_to "Add New Movie", new_movie_path %> -->
<!-- here I can use this (<%= @movies %>) this is rails instance variable that will grab the arry from the controller it is the erb tags (<%= %>, <% %>) it should look like this -->
<!-- Below is the code done with a html5 format to givee it
better structure -->
<% @movies.each do |movie| %>
  <article class="movie">
    <header>
    <%= image_tag(movie.image_file_name) %>
      <h2><%= link_to movie.title, movie %></h2>
      <h3><%= pluralize(movie.capacity, 'spot') %></h3>
    </header>
    <p>
      <h3><%= movie.variety %></h3>
    </p>
    <table>
      <tr>
        <th>Released:</th>
        <td><%= movie.released_on.to_s(:long) %></td>
      </tr>
      <tr>
        <th>Rating:</th>
        <td><%= movie.rating %></td>
      </tr>
      <tr>
        <th>Total Gross:</th>
        <td><%= number_to_currency(movie.total_gross) %></td>
      </tr>
    </table>
  </article>
<% end %>
</div>
<div class="large-4 columns">.</div>
</body>
<!-- <ul>

<% @movies.each do |movie| %>
   
     <h2><%= movie.title %></h2>

	     <h3><%= movie.variety %></h3>
	 
        <h3>Rating</h3><%= movie.rating %>
     <h3>Gross</h3><%= number_to_currency(movie.total_gross) %>
     <h3>When</h3>
     <p>
     <%= movie.released_on %>
     </p>

  
   <% end %> 

</ul>    -->   
<!-- <ul> 

<li>The Equalizer</li>
<li>The Judge</li>
<li>The Book Of Life</li>
<li>John Wick</li>
<li>Gone Girl</li>
<li>Dracula Untold</li>
<li>Fury</li>
	
</ul> -->

app/views/movies/new.html.erb
<%= render 'form' %>
<!-- The below was commented out and a Partials under views
/movies _form.html.erb -->
<!-- <h1>Add New Movies</h1> -->
<!-- <p>Find me in app/views/movies/new.html.erb</p> 



<%= form_for(@movie) do |f| %>
<p>
	<%= f. label :title %><br>
	<%= f. text_field :title, autofocus: true %>
</p>
<p>
	<%= f.label :variety %><br>
	<%= f.text_field :variety %>
</p>
<p>
	<%= f.label :rating %><br>
	<%= f.text_field :rating %>
</p>
<p>
	<%= f.label :total_gross %><br>
	<%= f.number_field :total_gross %>
</p>
<p>
	<%= f.label :released_on %><br>
	<%= f.datetime_select :released_on %>
</p>
<p>
	<%= f.submit %>
	<%= link_to "Cancel", movies_path %>
</p>
<% end -%> -->

app/views/movies/show.html.erb
<!-- <h1><%= @movie.title %></h1> -->
<article>
    <header>
      <%= image_for(@movie) %>
      <h1><%= @movie.title %></h1>
    </header>
    <p>
      <h3><%= @movie.variety %></h3>
    </p>
    <table>
      <tr>
        <th>Released:</th>
        <td><%= @movie.released_on.to_s(:long) %></td>
      </tr>
      <tr>
        <th>Rating:</th>
        <td><%= @movie.rating %></td>
      </tr>
      <tr>
        <th>Total Gross:</th>
        <td><%= number_to_currency(@movie.total_gross) %></td>
      </tr>
    </table>
    <h3>Capacity</h3>
    <p>
    	<%= pluralize(@movie.capacity, 'spot') %>
    </p>
    <%= link_to "Who's Review?", movie_reviews_path(@movie) %><br>
    <%= link_to "Write Review!", new_movie_review_path(@movie), 
           class: "button ok review" %>
  </article>

<!-- instead of using this<a href="/movies">All Movies</a>
used what below -->
<!-- this link move to the application page<%= link_to "All Movies", movies_path %> | -->
<%= link_to "Edit", edit_movie_path(@movie) %>
<%= link_to "Delete", movie_path(@movie), method: :delete, 
     data: {confirm: 'Are you sure?'} %>

app/views/movies/update.html.erb
<h1>Movies#update</h1>
<p>Find me in app/views/movies/update.html.erb</p>

app/views/reviews/index.html.erb
<header id="content-header">
	<h1>Reviews for <%= link_to(@movie.title, @movie) %></h1>
</header>

<!-- <ol> Below is a better way of displaying info
  <% @reviews.each do |review| %>
    <li>
      <p>
        <%= pluralize(review.stars, 'star') %> by <%= review.name %>:
      </p> 
      <p>
        <%= review.comment %>
      </p>
    </li>
  <% end %>
</ol> -->
<ol id="reviews">
  <% @reviews.each do |review| %>
    <li>
      <span class="review"><%= pluralize(review.stars, 'star') %></span>
      <span class="user">by <%= review.name %></span>
      <span class="date"><%= time_ago_in_words(review.created_at) %> ago</span>
      <p>
        &quot;<%= review.comment %>&quot;
      </p>
    </li>
  <% end %>
</ol>

app/views/reviews/new.html.erb
<header id="content-header">
	<h1>New Review for <%= link_to @movie.title, @movie %></h1>
</header>

<%= form_for([@movie, @review]) do |f| %>
<fieldset>
	<ol>
		<li class="required">
		   <%= f.label :name %>
		   <%= f.text_field :name, size: 40, autofocus: true %></li><br>
		 <li class="required">
		   <%= f.label :stars %>
		   <%= f.select :stars, 
		                Review::STARS, prompt: "Pick one" %>
		  </li><br>
		  <li class="required">
		   <%= f.label :commet %>
		   <%= f.text_field :comment, size: 50 %>
		  </li>
	</ol>
	<p>
		<%= f.submit %>
		<%= link_to "Cancel", movies_path, class: "button" %>
	</p>
</fieldset>
<% end %>

app/views/reviews/show.html.erb
<%= link_to "Edit", edit_movie_path(@movie) %>
<%= link_to "Delete", movie_path(@movie), method: :delete, 
     data: {confirm: 'Are you sure?'} %>